"""
Each new term in the fibonacci sequence is generated by adding the previous two terms.


By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 4 million,
find the sum of the even-valued terms.
"""

def fibonacci(n):
    a, b = 0, 1
    sum = 0
    while a < n:
        if a % 2 == 0:
            sum += a

        a, b = b, a + b
    return sum

print("sum of even valued pairs: ", fibonacci(4000000))

